### ISSUE TITLE
DISPLAY keyword in FILE-CONTROL

### ISSUE THREAD

**Issue by albertolovato** [uwol/cobol85parser#10]
The parser does not expect DISPLAY keyword not referring to the printing statement, as in
```
file-control.
    select standard-input assign to keyboard.
    select standard-output assign to display.
```

**Comment by uwol** [comment]
Thanks, you found a bug! Fixed in a6886eab6e8f4a5616a4d2db42dcd6a811a43ed0. Added a unit test.
