### ISSUE TITLE
DATA RECORD not processed

### ISSUE THREAD

**Issue by Reinhard-Prehofer** [uwol/cobol85parser#22]
[ISSUE14.CBL.txt](https://github.com/uwol/cobol85parser/files/1181310/ISSUE14.CBL.txt)

The DATA RECORD inside a FD seems to be ignored or not parsed correctly.
Also no idea, why the Ausgabe Structure is not parsed.
best refer to the simple sample.

```
Preprocessing file ISSUE14.CBL.
Preprocessing file ISSUE14.CBL.
Parsing file ISSUE14.CBL.
Collecting units in file ISSUE14.CBL.
Analyzing program units of compilation unit ISSUE14.
call to unknown data element D111E-DATEI
Analyzing identification divisions of compilation unit ISSUE14.
Analyzing environment divisions of compilation unit ISSUE14.
Analyzing data divisions of compilation unit ISSUE14.
Analyzing procedure divisions of compilation unit ISSUE14.
Analyzing statements of compilation unit ISSUE14.
call to unknown data element aus-vor
call to unknown data element aus-text
call to unknown data element aus-text
call to unknown data element ausgabe
```

**Comment by uwol** [comment]
Thanks, you found two bugs. 

1. Case-sensitive identifiers could not be resolved
2. Data description entries in file description entries could not be resolved from DATA RECORD clauses

Fixed in a2922058cb515dbd2131061cf556c40186c6a993, including unit test.
