### ISSUE TITLE
(too) rigid check of program-id. xxxx (NO DOT)

### ISSUE THREAD

**Issue by Reinhard-Prehofer** [uwol/cobol85parser#33]
Once again - same "erro" category like previous issue.
We do have several programs where the name of the program-id is not terminated with a DOT. 
(Sure the grammar insists on a dot - but most compilers dont check/insist on a DOT to terminate the name ...)

thus the parser runs into the next error:
```
Parsing file AAA02.cbl.
line 5:7 mismatched input 'ENVIRONMENT' expecting {COMMON, DEFINITION, INITIAL, IS, LIBRARY, DOT_FS}
Collecting units in file AAA02.cbl.

```
Cobollines with the incorrect declaration.

```
000010 IDENTIFICATION DIVISION.                          
000050 PROGRAM-ID.       AAA02 
000060******************************************************************07.05.15
      * not DOT after the name of the program-id !!!
```

Suggestion: though the parser is acting correctly - reality shows that most of the declarations 
like author or date-written or remarks etc (till input-output section) should be parsed with a rather error-forgiving algorithm.

**Comment by uwol** [comment]
I have relaxed the grammar for identification division entries such as the program id in 048043e2c08957201815844d713bdb21ec3a042c. Now, a DOT_FS is not required. Added a [unit test](https://github.com/uwol/cobol85parser/blob/048043e2c08957201815844d713bdb21ec3a042c/src/test/java/io/proleap/cobol/asg/identification/fixed/IdentificationDivisionWithoutDotsTest.java#L30).

Thanks!
