### ISSUE TITLE
call to unknown data element fort-struktur

### ISSUE THREAD

**Issue by Reinhard-Prehofer** [uwol/cobol85parser#34]
Not sure what really causes the parser to have problems with the data structure inside the attached cobol program.
The original data structure of the customer is much more complicated, including redefines and occurs as well ...

```
       01  FORT-Struktur.
           05 FORT-ANZ             PIC S9(7).
           05 FORT-TAB .
             10  C1FONEU.
               15 P8000                     PIC  X(14).
               15 PG8100.
                 20 PG8028-gruppe .
                   25 P8028               PIC  9(3).
                   25 P8028-N             PIC  9(2).
                 20 P8028-S               PIC  X(3).
```
Parser issues the following message:
`call to unknown data element fort-struktur
`
[a2612ABS.CBL.txt](https://github.com/uwol/cobol85parser/files/1212291/a2612ABS.CBL.txt)

**Comment by uwol** [comment]
This was a bug, which occurred due to case-sensitive identifier resolving.

Same as in #22, fixed yesterday with a2922058cb515dbd2131061cf556c40186c6a993. However, added a unit test for the code provided in this issue.

Thanks for issuing!
