### ISSUE TITLE
Data description entry not parsed correctly

### ISSUE THREAD

**Issue by albertolovato** [uwol/cobol85parser#36]
In parsing the following code, taken from [cobol-unit-test](https://github.com/neopragma/cobol-unit-test), the `DataDescriptionEntry` corresponding to BINARY has getName() that returns `null`.

       01  BINARY.
           05  THE-REMAINDER      PIC S9(4).
           05  THE-QUOTIENT       PIC S9(4).
           05  THE-DIVISOR        PIC S9(4).
           05  OFFSET             PIC S9(4).

**Comment by uwol** [comment]
Thanks, you found a bug! Fixed in 97a88d2f5e93dba119e4588deba12c754430a49b
