### ISSUE TITLE
Extra spaces in ID division lead to parsing errors

### ISSUE THREAD

**Issue by albertolovato** [uwol/cobol85parser#44]
Extra spaces before some paragraphs in identification division lead to errors, as in the following example, with 8 spaces instead of 7 before AUTHOR and DATE-WRITTEN:

`

       IDENTIFICATION DIVISION.
        PROGRAM-ID.       test1.
        AUTHOR.           Alberto.
        DATE-WRITTEN.     6/12/17.
`

`java.lang.RuntimeException: syntax error in line 3:26 mismatched input 'Alberto' expecting <EOF>
...`

Extra spaces don't seem to matter before PROGRAM-ID

**Comment by uwol** [comment]
Oh, you are right, thanks! Fixed in 04c46dd2bd7df9888a5fd09580ac3e12aa42416f and added 3 unit tests so it doesn't happen again.
