### ISSUE TITLE
Counterintuitive names for DIVIDE sub-statement

### ISSUE THREAD

**Issue by albertolovato** [uwol/cobol85parser#47]
Sub-statements of divide (and corresponding parser methods) have counterintuitive names: divideIntoStatement contains a GIVING keyword, while divideIntoGivingStatement does not contain it.

**Comment by uwol** [comment]
Thanks, you are right. Fixed in 6716fa8d8860c1713dfd1ab7b48eb9cd3d35a4ff. 

Issues like this one regarding the consistency/quality of the parser are very welcome!
