### ISSUE TITLE
Empty SOURCE-COMPUTER paragraph leads to parsing error

### ISSUE THREAD

**Issue by albertolovato** [uwol/cobol85parser#60]
The following code gives the exception:
`java.lang.RuntimeException: syntax error in line 30:7 mismatched input 'SPECIAL-NAMES' expecting {ABORT, AS, ASCII...`
even if the compiler does not complain about the missing computer name in the SOURCE-COMPUTER paragraph.
`

       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER.
       SPECIAL-NAMES.
               DECIMAL-POINT IS COMMA.
`

**Comment by uwol** [comment]
Thanks, fixed in b4a293eaf364a7214d911a81a69ae7aa223982ed for SOURCE-COMPUTER and OBJECT-COMPUTER paragraphs. Added a unit test.
