### ISSUE TITLE
Wrong name for method

### ISSUE THREAD

**Issue by albertolovato** [uwol/cobol85parser#63]
When parsing the statement
`DIVIDE y BY x GIVING x z.`,
the method `DivideStatement#getDivisorValueStmt()` returns `y`, the same as in the case `INTO`, but in this case `y` is the _dividend_, not the _divisor_

**Comment by uwol** [comment]
Ok, so `DivideStatement#getDivisorValueStmt()` could be both a dividend or divisor, depending on the divide statement type. As I want to keep the ASG simple, I simply renamed it to `DivideStatement#getOperandValueStmt()` in 231f2f983b9275097b696adb634724cf562cd25d. 

Hope that this fits well. Thanks for issuing!
